<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Override;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260301210036 extends AbstractMigration
{
	#[Override]
	public function getDescription(): string
	{
		return 'Create simulations table with optimistic locking support';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			sql: 'CREATE TABLE simulations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dimension INT NOT NULL, species_count INT NOT NULL, iterations_count INT NOT NULL, status VARCHAR(20) NOT NULL, species_types JSON NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))'
		);
	}

	#[Override]
	public function down(Schema $schema): void
	{
		$this->addSql(sql: 'DROP TABLE simulations');
	}
}
